### ISSUE TITLE
fix version, dependency

### ISSUE THREAD

**Issue by jja** [attentif/metalsmith-markdown-remarkable#3]
#1 and #2 at https://github.com/attentif/metalsmith-markdown-remarkable/compare/1.0.0...1.0.1#diff-b9cfc7f2cdf78a7f4b91a753d10865a2 have rather broken things for me. You updated remarkable to 2.0.0 which is a **breaking backwards-incompatible** change (they don't really say anything about it, but I cannot use my existing code (or even get it to work with major changes)). It is **very** disruptive to introduce this change as a tertiary version number "quick fix". In fact, you need not have done anything, your old version specifier for remarkable allows npm to fetch remarkable 1.7.4 which contains the security fix without breaking the remarkable API.

See:

* https://docs.npmjs.com/getting-started/semantic-versioning
* https://semver.npmjs.com/
  - in the "pick a package" input, enter "remarkable"
  - in the "enter a range" input, enter "^1.7.1" or "^1.7.4"

Please consider performing the following actions:

1. rescind your version 1.0.1
1. re-issue a clone of 1.0.0 as new version 1.0.2
1. issue version 1.0.3 which uses the remarkable version specifier `"^1.7.4"`

If you wish to update to remarkable 2.x, please do so in a matching major version number (2.0.0) and add clear documentation about versions in `README.md`. In the future, I suggest keeping your major version number the same as the major version number of the remarkable you specify.

Thank you.

**Comment by sgoumaz** [comment]
Thank _you_ for your care and exemplary message. It was indeed absolutely careless for me to upgrade to Remarkable 2.0.0 while just bumping the revision number. So now:

- v1.0.2 bundles Remarkable ^1.7.4 (I didn't see a need to republish v1.0.0)
- v2.0.0 bundles Remarkable ^2.0.0

I hope that fixes it. Thanks again.

**Comment by jja** [comment]
Thank you for your quick attention. It does seem to fix the situation, and gives us time to deal with the remarkable changes. Thank you for providing this package. It has been very helpful to me.
